### ISSUE TITLE
Contribute to other languages

### ISSUE THREAD

**Issue by cmstead** [SadeghPM/sql-vscode-snipptes#1]
Would it be reasonable to contribute snippets to other languages aside from just SQL?

I'm currently on a team that is working in TypeScript, and our data layer contains some raw (parameterized) queries. It would be awesome if we could generate the base query from a snippet.

I'd be glad to PR the change if it makes life easier for you.

Thanks so much for your work on this!

**Comment by SadeghPM** [comment]
Hi @cmstead 
wellcome
